Add some tests for already resolved issue #1222
BlueBrain/nexus pull request #1478
Opened 2020-08-20 14:40 UTC by imsdu

#1222 seems already fixed

I just completed the test to avoid a regression which may occur.

2020-08-20 15:37 UTC, umbreak approved these changes

2020-08-20 15:59 UTC, bogdanromanx requested changes
This still doesn't test the very specific case of retrieving a resource based on the schema uuid and resource uuid as path segments. (just uuids, no prefixes, no names, no url encodings)

2020-08-21 08:38 UTC, bogdanromanx submitted a review, later dismissed

2020-08-24 06:44 UTC, bogdanromanx approved these changes

2020-08-24 06:58 UTC, merged