Expose the permissions events through the Permissions contract
BlueBrain/nexus pull request #1659
Opened 2020-09-30 13:17 UTC by bogdanromanx

2020-09-30 13:36 UTC, umbreak requested changes
Not convinced about the offset as generic type

2020-09-30 13:36 UTC, umbreak commented on delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/Permissions.scala
> +trait Permissions[Offset] {
It has to be a generic type? Cannot be an abstract type? We are creating a lot of unnecessary noise having it as a type parameter (like `Permissions[_]` or `Permissions[Nothing]`)

2020-09-30 14:19 UTC, umbreak approved these changes

2020-09-30 14:21 UTC, wwajerowicz approved these changes

2020-10-01 06:58 UTC, umbreak requested changes
I'm still not sure if this generic type is worth it. Did you try wrapping the events response in an IO. would that work?

2020-10-02 10:45 UTC, merged