Added Organization routes
BlueBrain/nexus pull request #1724
Opened 2020-10-23 14:29 UTC by umbreak

Fixes https://github.com/BlueBrain/nexus/issues/1684

2020-10-23 15:01 UTC, bogdanromanx approved these changes

2020-10-23 15:04 UTC, imsdu requested changes

2020-10-23 15:04 UTC, imsdu commented on delta/app/src/main/scala/ch/epfl/bluebrain/nexus/delta/routes/OrganizationsRoutes.scala
> +class OrganizationsRoutes(identities: Identities, organizations: Organizations)(implicit
docs

2020-10-23 15:05 UTC, bogdanromanx requested changes
Add module bindings and include the routes in Main.

2020-10-23 15:51 UTC, imsdu requested changes

2020-10-23 15:51 UTC, imsdu commented on delta/app/src/main/scala/ch/epfl/bluebrain/nexus/delta/wiring/OrganizationsModule.scala
> +  make[PaginationConfig].from((cfg: OrganizationsConfig) => cfg.pagination)
Twice ?

2020-10-23 15:51 UTC, imsdu commented on delta/app/src/main/scala/ch/epfl/bluebrain/nexus/delta/wiring/OrganizationsModule.scala
> +    cfg.database.flavour match {
We could have a helper for this

2020-10-23 16:42 UTC, imsdu approved these changes

2020-10-26 08:10 UTC, bogdanromanx requested changes
still requires including the routes in the Main class

2020-10-26 08:26 UTC, bogdanromanx approved these changes

2020-10-26 08:31 UTC, merged