Added AccessUrl
BlueBrain/nexus pull request #1756
Opened 2020-11-05 16:24 UTC by umbreak

- Added `_self` (AccessUrl) metadata field to all resource types.
- Refactored `ResourceF` to only contain one type parameter.

2020-11-05 17:59 UTC, imsdu requested changes

2020-11-05 17:59 UTC, imsdu commented on delta/app/src/main/scala/ch/epfl/bluebrain/nexus/delta/wiring/DeltaModule.scala
> +  private val aclsCtx          = ioJsonContentOf("/contexts/acls.json").memoizeOnSuccess
I think it would better if we define the Context (Iri + IO) in the same place.

2020-11-05 17:59 UTC, imsdu commented on delta/sdk/src/test/resources/resource-compacted.jsonld
> +  "_createdBy": "http://example.com/anonymous",
Better to replace with localhost

2020-11-06 10:59 UTC, bogdanromanx approved these changes

2020-11-06 11:07 UTC, imsdu approved these changes

2020-11-06 11:12 UTC, merged