Added support for multiple root entries
BlueBrain/nexus pull request #1838
Opened 2020-11-27 16:04 UTC by umbreak

This work allows to have Json-LD documents with [single](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22%40type%22%3A%22Person%22%2C%22name%22%3A%22Jane%20Doe%22%7D) or [multiple](https://json-ld.org/playground/#startTab=tab-expanded&json-ld=%7B%22%40context%22%3A%7B%22%40vocab%22%3A%22http%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F%22%7D%2C%22%40graph%22%3A%5B%7B%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Flibrary%2Fthe-republic%22%2C%22title%22%3A%22The%20Republic%22%7D%2C%7B%22%40id%22%3A%22http%3A%2F%2Fexample.org%2Flibrary%2Fthe-hobbit%22%2C%22title%22%3A%22The%20Hobbit%22%7D%5D%7D) root entries.

This can be useful for posting resources in certain situations (this work is currently only partially supported on 1.4.x) and also enables us to have the "fat schema" containing all the owl:imports resolved in the same expanded jsonld document.

I've also removed unnecessary methods on compaction/expansion

2020-11-27 17:05 UTC, imsdu requested changes

2020-11-27 17:41 UTC, umbreak commented on delta/rdf/src/main/scala/ch/epfl/bluebrain/nexus/delta/rdf/graph/Graph.scala
> +final case class Graph private (rootNode: IriOrBNode, model: Model, private val singleRoot: Boolean) { self =>
Yes it can, since there is always a primary node anyway.

2020-11-27 17:41 UTC, umbreak commented on delta/rdf/src/main/scala/ch/epfl/bluebrain/nexus/delta/rdf/graph/Graph.scala
> +final case class Graph private (rootNode: IriOrBNode, model: Model, private val singleRoot: Boolean) { self =>
I wouldn't bother with an ADT for this

2020-11-27 17:42 UTC, umbreak commented on delta/rdf/src/main/scala/ch/epfl/bluebrain/nexus/delta/rdf/jsonld/CompactedJsonLd.scala
> +      frameOnRootId: Boolean = false
We can but I find it more descriptive like this:
```scala
CompactedJsonLd(id, ctx, input, frameOnRootId = true|false)
```

Than having:

```scala
CompactedJsonLd.frameOnRootId(id, ctx, input)
```

2020-11-30 07:28 UTC, bogdanromanx submitted a review, later dismissed

2020-11-30 07:30 UTC, imsdu approved these changes

2020-11-30 07:46 UTC, imsdu approved these changes

2020-11-30 07:48 UTC, bogdanromanx approved these changes

2020-11-30 07:52 UTC, merged