Fix stream supervisor stop/restart/termination on error
BlueBrain/nexus pull request #2041
Opened 2021-02-15 16:18 UTC by imsdu

2021-02-15 16:24 UTC, bogdanromanx approved these changes

2021-02-15 16:25 UTC, umbreak requested changes

2021-02-15 16:25 UTC, umbreak commented on delta/sourcing/src/main/scala/ch/epfl/bluebrain/nexus/sourcing/projections/stream/StreamSupervisorBehavior.scala
> +                  Task.delay(logger.debug(s"Stream $streamName has been successfully completed.")) >> onStreamFinalize
`UIO.delay`

2021-02-15 16:25 UTC, umbreak commented on delta/sourcing/src/main/scala/ch/epfl/bluebrain/nexus/sourcing/projections/stream/StreamSupervisorBehavior.scala
> +                  Task.delay(logger.error(s"Stream $streamName events has failed.", e)) >> onStreamFinalize
same

2021-02-15 16:25 UTC, umbreak commented on delta/sourcing/src/main/scala/ch/epfl/bluebrain/nexus/sourcing/projections/stream/StreamSupervisorBehavior.scala
> +                  Task.delay(logger.warn(s"Stream $streamName got cancelled.")) >> onStreamFinalize
same

2021-02-16 10:45 UTC, umbreak approved these changes

2021-02-16 10:47 UTC, merged