Introduce convention for plugin configuration
BlueBrain/nexus pull request #2242
Opened 2021-04-09 13:10 UTC by imsdu

Fixes #2074

2021-04-09 13:58 UTC, umbreak requested changes
I'm not sure if that's exactly what @bogdanromanx had in mind. To me, just to prefix the configuration block with `plugins` is not bringing anything.
We probably can wait until @bogdanromanx to know what was all this about.

2021-04-09 14:42 UTC, imsdu commented
The namespace allows to isolate them from other entries so it is valuable as it allows to better identify them and perform checks.

The issue is discussing about a configuration root not so much about the checks.

About the checks, we can imagine that the composite views plugin could change a setting on the ES / BG plugin such as changing a timeout / a retry strategy.

2021-04-09 14:51 UTC, umbreak commented
Ok. I don't see much of a benefit. But if you guys thing that's "nicer", yeah sure.

2021-04-12 08:21 UTC, bogdanromanx approved these changes

2021-04-13 06:47 UTC, merged