Updated composite views docs
BlueBrain/nexus pull request #2446
Opened 2021-05-17 16:07 UTC by umbreak

![screencapture-localhost-4001-docs-delta-api-current-views-composite-view-api-html-2021-05-17-18_03_14](https://user-images.githubusercontent.com/1430863/118520678-89093400-b73a-11eb-9f55-1366c80c6d2b.png)

![screencapture-localhost-4001-docs-delta-api-current-views-composite-view-api-html-2021-05-17-18_03_14-2](https://user-images.githubusercontent.com/1430863/118520646-81e22600-b73a-11eb-9d80-9f2efb629b28.png)

2021-05-17 16:28 UTC, bogdanromanx approved these changes

2021-05-17 18:53 UTC, wwajerowicz requested changes

2021-05-17 18:53 UTC, wwajerowicz commented on docs/src/main/paradox/docs/delta/api/current/assets/views/composite/fetched.json
> +{"@context":["https://bluebrain.github.io/nexus/contexts/composite-views.json","https://bluebrain.github.io/nexus/contexts/metadata.json"],"@id":"http://music.com/composite_view","@type":["View","Com
this file could use better formatting.

2021-05-17 18:53 UTC, wwajerowicz commented on docs/src/main/paradox/docs/delta/api/current/views/composite-view-api.md
> +The specified list of identities will be used to retrieve the resources from the project. The target project must have `events/read` permissions in order to read events.
The identities must have `events/read` permission on the target project ....

2021-05-17 18:53 UTC, wwajerowicz commented on docs/src/main/paradox/docs/delta/api/current/views/composite-view-api.md
> +Updating a view creates a new Elasticsearch index and deletes the existing one. The indexing process will start from the
It creates a new index/namespace for all the projection, not only for Elasticsearch.

2021-05-17 18:53 UTC, wwajerowicz commented on docs/src/main/paradox/docs/delta/api/current/views/composite-view-api.md
> +Locks the view, so no further operations can be performed. It also stops indexing any more resources into it and deletes the underlying index.
and deletes all the underlying Elasticsearch indices and Blazegraph namespaces.

2021-05-17 18:53 UTC, wwajerowicz commented on docs/src/main/paradox/docs/delta/api/current/views/composite-view-api.md
> +Deprecating a view deletes the view index, making the view not searchable.
Same here:  deletes all the underlying Elasticsearch indices and Blazegraph namespaces.

2021-05-18 07:39 UTC, wwajerowicz approved these changes

2021-05-18 07:51 UTC, bogdanromanx approved these changes

2021-05-18 07:56 UTC, imsdu approved these changes

2021-05-18 08:14 UTC, merged