Improve integration tests
BlueBrain/nexus pull request #2511
Opened 2021-06-02 15:26 UTC by imsdu

Fixes #2491 

* Limit memory for the different components
* Refresh more aggressively
* Make integration tests work with PostgreSQL
* Do Keycloak related stuff at bootstrap
* Improve error message with context
* Make parallel calls where it is possible

2021-06-02 15:32 UTC, umbreak approved these changes

2021-06-02 17:53 UTC, bogdanromanx requested changes

2021-06-02 17:53 UTC, bogdanromanx commented on tests/docker/docker-compose-cassandra.yml
>  #  Uncomment the following lines to run a local cluster #
Please also update the entries for the clustered config.

2021-06-02 17:53 UTC, bogdanromanx commented on tests/docker/docker-compose-ci.yml
same as above, please also update delta2 and delta3

2021-06-02 17:53 UTC, bogdanromanx commented on tests/docker/docker-compose-postgres.yml
>    #  Uncomment the following lines to run a local cluster #
same as above

2021-06-03 13:58 UTC, bogdanromanx approved these changes

2021-06-03 14:42 UTC, merged