Stopped views when they are idle
BlueBrain/nexus pull request #2512
Opened 2021-06-02 16:11 UTC by umbreak

Fixes https://github.com/BlueBrain/nexus/issues/2461

2021-06-07 13:28 UTC, imsdu requested changes

2021-06-07 13:28 UTC, imsdu commented on delta/plugins/blazegraph/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/blazegraph/indexing/BlazegraphOnEventInstant.scala
> +    val idleTimeout = config.idleTimeout.minus(config.idleTimeout.div(10).min(1.minute)) // allow for some tolerance
How did you come up with this formula ? Substracting a minute is not enough ?

2021-06-07 13:28 UTC, imsdu commented on delta/plugins/blazegraph/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/blazegraph/indexing/BlazegraphOnEventInstant.scala
> +      val currentProjectViews = views.list(OnePage, searchParams(project), ResourceF.defaultSort).map(_.sources)
You will get aggregate views here too no ?

2021-06-07 13:28 UTC, imsdu commented on delta/plugins/elasticsearch/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/indexing/ElasticSearchOnEventInstant.scala
> +      val currentProjectViews = views.list(OnePage, searchParams(project), ResourceF.defaultSort).map(_.sources)
Same, you will get aggregate views no ?

2021-06-07 14:23 UTC, umbreak commented on delta/sdk-views/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/views/indexing/IndexingStreamAwake.scala
> +      RetryStrategy[Throwable](keyValueStoreConfig.retry, _ => true, logError(logger, "IndexingStreamAwake"))
I think It is alright to have the same configuration than for `ProjectsCounts` for now. Let's see later on.

2021-06-08 07:39 UTC, wwajerowicz approved these changes

2021-06-10 11:29 UTC, wwajerowicz approved these changes

2021-06-15 14:55 UTC, imsdu approved these changes

2021-06-16 06:34 UTC, merged