Added token expiration comments, changed limits
BlueBrain/nexus pull request #2672
Opened 2021-08-09 09:57 UTC by eugeniashurko

Edits to the MOOC notebooks:

- Added comments on the expiration of the access token
- Increased limit of the fetched resources
- Removed display limit

2021-08-09 10:35 UTC, MFSY approved these changes

2021-08-10 07:09 UTC, MFSY requested changes
Why removing the skinks context ?

it is fetched by the notebooks and when initializing a forge session

2021-08-10 07:38 UTC, eugeniashurko commented
> Why removing the skinks context ?
> 
> it is fetched by the notebooks and when initializing a forge session

@MFSY  what is skinks?

I added `embeddings` to the local context file as @annakristinkaufmann suggested:
```
"embedding": {
      "@id": "nsg:embedding",
      "@container": "@list"
    }
```

2021-08-10 10:40 UTC, MFSY commented
> > Why removing the skinks context ?
> > it is fetched by the notebooks and when initializing a forge session
> 
> @MFSY what is skinks?
> 
> I added `embeddings` to the local context file as @annakristinkaufmann suggested:
> 
> ```
> "embedding": {
>       "@id": "nsg:embedding",
>       "@container": "@list"
>     }
> ```
> 
> When this file will be updated remotely, what we will fetch is the new version with `embedding`

Okay. The change looked big compared to just adding embedding. It looked like the file the file content was being deleted.

2021-08-10 10:40 UTC, MFSY approved these changes

2021-08-10 10:48 UTC, merged