Implementing deployment stats
BlueBrain/nexus pull request #2766
Opened 2021-09-07 13:01 UTC by imsdu

Address part of #2528

2021-09-07 15:06 UTC, bogdanromanx requested changes
Also create a separate issue (or directly a PR) to handle recording metrics for Resources that have a distribution that are not Files in the system (binaries are described but not registered)

2021-09-07 15:06 UTC, bogdanromanx commented on delta/sourcing/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/projections/ProjectionStream.scala
> +            case ((acc, errors), msg: SuccessMessage[A]) if msg.offset.gt(acc.offset) && msg.warnings.nonEmpty =>
this will yield a warning and fail the build

2021-09-07 16:28 UTC, imsdu commented on delta/plugins/elasticsearch/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/metric/ProjectEventMetricsStream.scala
> +          .persistProgress(progress, projectionId, projection)
I will create an issue to address this in a different PR.
Only views are using kamon for now, the other streams don't.

2021-09-08 07:32 UTC, bogdanromanx requested changes

2021-09-08 07:32 UTC, bogdanromanx commented on delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/model/metrics/EventMetric.scala
> +            "short" -> tpe.toUri.toOption.flatMap(_.path.lastSegment).asJson
this should be Fragment or last segment

2021-09-08 10:28 UTC, bogdanromanx approved these changes

2021-09-08 10:45 UTC, merged