Fusion release notes
BlueBrain/nexus pull request #3083
Opened 2022-01-31 10:47 UTC by nicwells

Fixes https://github.com/BlueBrain/nexus/issues/2962

2022-02-10 09:08 UTC, imsdu requested changes

2022-02-10 09:08 UTC, imsdu commented on docs/src/main/paradox/docs/releases/v1.6-to-v1.7-migration.md
> +## Fusion Studios
Can you also add a `Delta` header for the first part of the migration ?

2022-02-11 11:04 UTC, imsdu approved these changes

2022-02-22 09:05 UTC, dhaneshnm approved these changes

2022-02-22 09:08 UTC, merged