Add API endpoint to get running projections
BlueBrain/nexus pull request #3550
Opened 2022-10-31 08:40 UTC by olivergrabinski

Closing #3531

2022-11-01 13:58 UTC, olivergrabinski commented
Supervision documentation page:

<img width="1261" alt="Screenshot 2022-11-01 at 14 57 15" src="https://user-images.githubusercontent.com/20188437/199250773-2c13cd4b-c5c9-4440-8ec9-d985d1ba2ee7.png">
<img width="1202" alt="Screenshot 2022-11-01 at 14 57 51" src="https://user-images.githubusercontent.com/20188437/199250782-cb4a0097-12d9-49b1-946f-e283defc3b5b.png">

2022-11-01 14:16 UTC, imsdu requested changes

2022-11-01 14:16 UTC, imsdu commented on delta/app/src/main/scala/ch/epfl/bluebrain/nexus/delta/routes/SupervisionRoutes.scala
> +    supervised: Task[List[SupervisedDescription]]
We should get an UIO here as we don't expect any kind of errors

2022-11-01 14:16 UTC, imsdu commented on delta/app/src/test/resources/supervision/supervision-running-proj-response.json
> +  "@context" : "https://bluebrain.github.io/nexus/contexts/supervision.json",
It looks like it requires a reformating from IntelliJ (there should not be a space between the end of `context` and the colon)

2022-11-01 14:16 UTC, imsdu commented on delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/Supervisor.scala
> +  def getRunningProjections(filterIgnored: Boolean = true): Task[List[SupervisedDescription]]
We should have an UIO and not a Task here

2022-11-01 14:16 UTC, imsdu commented on delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/stream/Supervisor.scala
> +        description <- supervised.traverse(_.description)
I guess we could use `traverseFilter` here ?

2022-11-01 14:16 UTC, imsdu commented on docs/src/main/paradox/docs/delta/api/assets/supervision/supervision-list.json
> +  "@context" : "https://bluebrain.github.io/nexus/contexts/supervision.json",
Same, needs a reformat

2022-11-01 14:16 UTC, imsdu commented on docs/src/main/paradox/docs/delta/api/supervision-api.md
> +This endpoint returns information about the projection supervisor.
This endpoint returns information about the projections running on the current node.

2022-11-01 14:16 UTC, imsdu commented on delta/app/src/test/scala/ch/epfl/bluebrain/nexus/delta/routes/SupervisionRoutesSpec.scala
> +    "return the correct running projections" in {
You could merge this test with previous one so that it checks both the http code and the response

2022-11-02 08:36 UTC, olivergrabinski commented
All comment should be addressed now 🙂

2022-11-02 08:41 UTC, imsdu approved these changes

2022-11-02 09:58 UTC, merged