Add name and description to Blazegraph views
BlueBrain/nexus pull request #3565
Opened 2022-11-07 13:10 UTC by olivergrabinski

#3195

2022-11-07 13:18 UTC, olivergrabinski commented
To review:
1. Both name and description are `String`s.
2. schema.org is not used in the blazegraph json-ld context

2022-11-09 09:57 UTC, imsdu requested changes

2022-11-09 09:57 UTC, imsdu commented on delta/plugins/blazegraph/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/blazegraph/BlazegraphScopeInitialization.scala
> +    name = None,
We need a default value here

2022-11-09 09:57 UTC, imsdu commented on delta/plugins/blazegraph/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/blazegraph/BlazegraphScopeInitialization.scala
> +    description = None,
Same

2022-11-09 13:20 UTC, olivergrabinski commented on delta/plugins/blazegraph/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/blazegraph/BlazegraphScopeInitialization.scala
> +    description = None,
Added defaults to `model`

2022-11-14 09:44 UTC, imsdu approved these changes

2022-11-14 10:19 UTC, merged