Use indexing revision to trigger Elasticsearch reindexing
BlueBrain/nexus pull request #3619
Opened 2023-01-13 14:49 UTC by olivergrabinski

#3569

2023-01-17 09:45 UTC, olivergrabinski commented
To do:
- [ ] Review `indexingRev` name

2023-01-17 13:26 UTC, imsdu requested changes

2023-01-17 13:26 UTC, imsdu commented on delta/plugins/elasticsearch/src/test/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/ElasticSearchViewsQuerySpec.scala
> +            val index = IndexLabel.unsafe(view.index.value)
`view.index` is an `IndexLabel`

2023-01-20 14:38 UTC, imsdu approved these changes

2023-01-25 12:55 UTC, merged