Update `Running Nexus` doc
BlueBrain/nexus pull request #3874
Opened 2023-05-08 16:06 UTC by olivergrabinski

2023-05-22 08:48 UTC, imsdu requested changes

2023-05-22 08:48 UTC, imsdu commented on docs/src/main/paradox/docs/getting-started/running-nexus/index.md
>  @link:[Docker Swarm](https://docs.docker.com/engine/swarm/){ open=new } as they offer good management capabilities, discovery, load
Docker Swarm and Openshift need to be deleted

2023-05-22 12:15 UTC, carolili commented on docs/src/main/paradox/docs/getting-started/running-nexus/index.md
> +Nexus Delta takes advantage of PostgreSQL's @link:[Table Partitioning](https://www.postgresql.org/docs/current/ddl-partitioning.html) feature. This allows for improved query performance, as well faci
`as well facilitates` -> `as well as facilitates` ? It seems like some word is missing with only `as well facilitates` 🤔

2023-05-22 12:17 UTC, carolili commented on docs/src/main/paradox/docs/getting-started/running-nexus/index.md
> +MD5 hashing is used in order to guarantee a constant partition name length (PostgreSQL table names are limited to 63 character by default), as well as to avoid any special characters that might be al
The last `PostgreSQl` -> `PostgreSQL`

2023-05-22 12:17 UTC, carolili commented on docs/src/main/paradox/docs/getting-started/running-nexus/index.md
> +While Nexus Delta provides table partitioning out-of-the-box, it is primarily addressing the case where the data is more or less uniformly spread out across multiple projects. If however there is one
`case-by-cases` -> `case-by-case` ?

2023-05-23 13:37 UTC, imsdu approved these changes

2023-06-08 12:59 UTC, imsdu approved these changes

2023-06-08 13:00 UTC, merged