forbid nexus metadata fields in user payloads
BlueBrain/nexus pull request #4013
Opened 2023-06-29 09:08 UTC by shinyhappydan

Fixes #3935

2023-06-29 09:09 UTC, shinyhappydan commented
Needs at least one integration test probably

2023-07-12 08:26 UTC, shinyhappydan commented
Is it worth doing this refactor now? The code is already working, and if the structure isn't ideal then that's annoying but we probably have bigger problems to work on. If this feedback was earlier then it would make sense to action it, but now it's as easy to refactor tomorrow as it is today and this doesn't feel high priority. Let me know what you think @imsdu

2023-07-17 16:00 UTC, imsdu requested changes

2023-07-17 16:00 UTC, imsdu commented on delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/resources/NexusSource.scala
> +            Left(DecodingFailure(s"Metadata field(s) found in payload: ${underscoreFields.mkString(", ")}", c.history))
Replace `Metadata fields` by something like `Fields starting by _` as all fields starting by _ are prohibited

2023-07-17 16:00 UTC, imsdu commented on delta/sdk/src/main/scala/ch/epfl/bluebrain/nexus/delta/sdk/resources/NexusSource.scala
> +                      s"values can be 'strict' or 'lenient'"
Values can only be 'strict' or 'lenient'

2023-07-20 09:30 UTC, imsdu commented on delta/app/src/main/scala/ch/epfl/bluebrain/nexus/delta/routes/ResourcesRoutes.scala
> +                              .create(ref, schema, source.value)
The idea was also to change the create and update method to take a `NexusSource` instead of a json but it can be done in another PR.

2023-07-20 09:35 UTC, imsdu requested changes

2023-07-20 09:35 UTC, imsdu commented on docs/src/main/paradox/docs/delta/api/resources-api.md
> +@@@ note { .warning }
I think we can only add it once at the top of the page

2023-07-20 09:35 UTC, imsdu commented on docs/src/main/paradox/docs/releases/v1.9-release-notes.md
> +It is now forbidden for JSON payloads to contain fields beginning with underscore (_). This can be disabled be setting `app.resources.decoding-option` to `lenient`
We need to make it clearer that it is discouraged

2023-07-20 13:40 UTC, imsdu submitted a review, later dismissed

2023-07-20 16:26 UTC, imsdu approved these changes

2023-07-20 16:27 UTC, merged