Add endpoint to list indexing errors for Elasticsearch
BlueBrain/nexus pull request #4109
Opened 2023-07-26 10:50 UTC by imsdu

Related to #3979 

* Split further `ElasticsearchViewsRoutes` to reduce complexity
* Add missing total count for the listing

2023-07-26 10:51 UTC, imsdu commented on delta/plugins/elasticsearch/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/routes/ElasticSearchQueryRoutes.scala
> -              (pathEndOrSingleSlash & operationName(s"$prefixSegment/resources")) {
As those are not used anymore

2023-07-26 11:49 UTC, shinyhappydan reviewed
I'm not sure I understand what the goal of this PR is but I've left comments on some things I understood

2023-07-26 11:49 UTC, shinyhappydan commented on delta/sourcing-psql/src/main/scala/ch/epfl/bluebrain/nexus/delta/sourcing/projections/ProjectionErrors.scala
> +    */
This comment should refer to count rather than list

These fields are clear from the name, consider removing the comments

2023-07-26 11:49 UTC, shinyhappydan commented on delta/sourcing-psql/src/test/scala/ch/epfl/bluebrain/nexus/delta/sourcing/projections/FailedElemLogStoreSuite.scala
> +    store.count(project1, projection12, before).assert(2L)
These test names seem too fixture-specific. Isn't the important thing (giving the first test as an example) that's you're listing failures of a certain projection after a certain time? The specific time and metadata (which isn't actually referred to in the test) doesn't help me understand what the test is supposed to do, it's actually making it harder

2023-07-27 12:13 UTC, olivergrabinski requested changes

2023-07-27 12:13 UTC, olivergrabinski commented on delta/plugins/elasticsearch/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/routes/ElasticSearchIndexingRoutes.scala
> +                          )
Doc should be updated at some point

2023-07-27 13:13 UTC, imsdu commented on delta/plugins/elasticsearch/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/routes/ElasticSearchIndexingRoutes.scala
> +                          )
Yep, I plan to do it last :)

2023-07-27 13:21 UTC, olivergrabinski approved these changes

2023-07-27 13:31 UTC, merged