Add endpoint to fetch Elasticsearch view mappings
BlueBrain/nexus pull request #4165
Opened 2023-08-15 14:03 UTC by olivergrabinski

New pass-through endpoint to ES mappings based on user's authorization

Closes #4142

2023-08-15 14:56 UTC, olivergrabinski commented on delta/plugins/elasticsearch/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/model/ElasticSearchViewRejection.scala
> +      id: String,
To be able to pass an IdSegment as well, thought the segment might not be fully expanded 🤔

2023-08-15 14:59 UTC, olivergrabinski commented on tests/src/test/scala/ch/epfl/bluebrain/nexus/tests/kg/ElasticSearchViewsSpec.scala
> +    }
Not sure what checks beyond the basic structure make sense

2023-08-15 14:59 UTC, olivergrabinski commented on delta/plugins/elasticsearch/src/main/scala/ch/epfl/bluebrain/nexus/delta/plugins/elasticsearch/ElasticSearchViewsQuery.scala
> +      view   <- aclCheck.authorizeForOr(project, permissions.write)(AuthorizationFailed).as(viewStore.fetch(id, project))
Authorization done in a similar fashion to the `query` functions

2023-08-15 15:31 UTC, imsdu requested changes

2023-08-15 15:31 UTC, imsdu commented on tests/src/test/scala/ch/epfl/bluebrain/nexus/tests/kg/ElasticSearchViewsSpec.scala
> +    "return the view's mapping" in {
We need other tests with a user with a missing permission and for a non-existing view

2023-08-16 07:38 UTC, imsdu approved these changes

2023-08-17 15:49 UTC, merged