Migrate Identities to Cats-effect
BlueBrain/nexus pull request #4288
Opened 2023-09-21 12:34 UTC by imsdu

Fixes #4251

2023-09-21 12:35 UTC, imsdu commented on delta/app/src/main/scala/ch/epfl/bluebrain/nexus/delta/routes/IdentitiesRoutes.scala
> -  )(implicit baseUri: BaseUri, s: Scheduler, cr: RemoteContextResolution, ordering: JsonKeyOrdering): Route =
Some of those start to go away :)

2023-09-21 12:37 UTC, imsdu commented on delta/kernel/src/main/scala/ch/epfl/bluebrain/nexus/delta/kernel/cache/LocalCache.scala
> +trait LocalCache[K, V] {
Equivalent of `KeyValueStore` but for CE.
Renamed as `KeyValueStore` name was some left over the period where it has a Caffeine implementation but also one relying on a distributed Akka cache

2023-09-21 13:15 UTC, shinyhappydan requested changes

2023-09-22 10:20 UTC, olivergrabinski approved these changes

2023-09-22 16:50 UTC, shinyhappydan approved these changes

2023-09-23 10:24 UTC, merged